### ISSUE TITLE
Sign in bug

### ISSUE THREAD

**Issue by kvanderheiden** [fajita12/socialOctopus#23]
When signing in with the testing account, clicking the sign-in button multiple times before sign-in occurs causes a runtime error. It can take a second for the app to redirect you from the sign-in page so a user could easily mistakenly think that they're first tap didn't register when in fact it did. Tapping it a second time produces the error.

Severity: Critical

Stack Trace:
Error: Uncaught (in promise): SyntaxError: Unexpected token u in JSON at position 0
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at http://localhost:8100/build/main.js:1521:37
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14976)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:4982:33)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14916)
    at r.run (http://localhost:8100/build/polyfills.js:3:10143)
    at http://localhost:8100/build/polyfills.js:3:20242
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4973:33)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15581)
    at c (http://localhost:8100/build/polyfills.js:3:19752)
    at http://localhost:8100/build/polyfills.js:3:20273
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4973:33)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15581)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:10834)
    at o (http://localhost:8100/build/polyfills.js:3:7894)
    at e.invokeTask [as invoke] (http://localhost:8100/build/polyfills.js:3:16823)
    at p (http://localhost:8100/build/polyfills.js:2:27648)
    at XMLHttpRequest.v (http://localhost:8100/build/polyfills.js:2:27893)

**Comment by agrimpandey** [comment]
Resolved. code in final_demo1

**Comment by I-Dont-Remember** [comment]
Just saw the same error in finaldemo1

**Comment by agrimpandey** [comment]
@I-Dont-Remember did you see this specific error when signing in? I don't see how that's possible since the sign in button is disabled after it's clicked. Are you sure this was in branch finaldemo1?

**Comment by I-Dont-Remember** [comment]
100% it was in finaldemo1 since once I changed to that branch i never left it and directory is still there, though I misread Kyle's bug.  It wasn't with multiple clicks but every time I logged in with `hey` it showed me that same stack trace right away on the homepage.  I did a refresh of everything after your response and now it appears to be gone, so something must have been up with my lab cache or something.  You're probably good but double check it just in case.
