### ISSUE TITLE
Error on Signout

### ISSUE THREAD

**Issue by frizzkitten** [fajita12/socialOctopus#25]
I opened the app with `ionic lab` then I logged in with the test account. Immediately after logging in I pressed Logout. The screen showed an error, shown below. If I close the error and try to sign in again, I get the same error again.

Severity: Blocker.

Error: Uncaught (in promise): SyntaxError: Unexpected token u in JSON at position 0
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at http://localhost:8100/build/main.js:1548:37
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14976)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:4982:33)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14916)
    at r.run (http://localhost:8100/build/polyfills.js:3:10143)
    at http://localhost:8100/build/polyfills.js:3:20242
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4973:33)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15581)
    at c (http://localhost:8100/build/polyfills.js:3:19752)
    at http://localhost:8100/build/polyfills.js:3:20273
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4973:33)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15581)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:10834)
    at o (http://localhost:8100/build/polyfills.js:3:7894)
    at e.invokeTask [as invoke] (http://localhost:8100/build/polyfills.js:3:16823)
    at p (http://localhost:8100/build/polyfills.js:2:27648)
    at XMLHttpRequest.v (http://localhost:8100/build/polyfills.js:2:27893)

**Comment by agrimpandey** [comment]
Please check the finaldemo1 branch and let me know if the error still exists. 
I have checked it and I don't get that error.
