### ISSUE TITLE
Runtime error on search

### ISSUE THREAD

**Issue by frizzkitten** [fajita12/socialOctopus#27]
I went to the search page and typed in "burn," then press the search button multiple times. An error came up on screen, shown below.

Severity: Not critical but fairly important to fix.

Error: Uncaught (in promise): TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at new SearchresultsPage (http://localhost:8100/build/main.js:158:47)
    at createClass (http://localhost:8100/build/vendor.js:12527:20)
    at createDirectiveInstance (http://localhost:8100/build/vendor.js:12364:37)
    at createViewNodes (http://localhost:8100/build/vendor.js:13802:53)
    at createRootView (http://localhost:8100/build/vendor.js:13692:5)
    at callWithDebugContext (http://localhost:8100/build/vendor.js:15093:42)
    at Object.debugCreateRootView [as createRootView] (http://localhost:8100/build/vendor.js:14394:12)
    at ComponentFactory_.create (http://localhost:8100/build/vendor.js:11313:46)
    at ComponentFactoryBoundToModule.create (http://localhost:8100/build/vendor.js:4275:29)
    at NavControllerBase._viewInit (http://localhost:8100/build/vendor.js:48755:44)
    at c (http://localhost:8100/build/polyfills.js:3:19752)
    at Object.reject (http://localhost:8100/build/polyfills.js:3:19174)
    at NavControllerBase._fireError (http://localhost:8100/build/vendor.js:48537:16)
    at NavControllerBase._failed (http://localhost:8100/build/vendor.js:48530:14)
    at http://localhost:8100/build/vendor.js:48577:59
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14976)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:4982:33)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14916)
    at r.run (http://localhost:8100/build/polyfills.js:3:10143)
    at http://localhost:8100/build/polyfills.js:3:20242

**Comment by frizzkitten** [comment]
realized this was already reported
